name = "sonia-final-backend"
main = "worker.js"
compatibility_date = "2024-02-28"

[[d1_databases]]
binding = "DB"
database_name = "SONIA_FINAL_DB"
database_id = "9d56f1df-f50a-4d62-955a-948f745ad51a" 
# (Vamos pegar esse ID no pr√≥ximo passo)